services:
  db:
    image: mysql:latest
    env_file:
      - .env
    ports: # bind localhost to container
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql # directory inside the container where MySQL by default its data files.
      - ./scripts/sql:/docker-entrypoint-initdb.d # initialize the database using any scripts found scripts/sql
volumes:
  mysql_data:
